server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: ayomide-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 3Cf3Hh31h2CHF5E1F1f43Gg4aD2Dhca3
    url: jdbc:mysql://monorail.proxy.rlwy.net:49323/railway
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0
