server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: ayomide-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: f4A2bAFhD-gg6dcebBbFEBh-6G3hf-F2
    url: jdbc:mysql://monorail.proxy.rlwy.net:38311/railway
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0
